#!/bin/bash
# change this file to your needs

echo "Adding some modules"

module add gcc-10.2

echo "#################"
echo "    COMPILING    "
echo "#################"

g++ -Wall -std=c++17 -O3 src/main.cpp -o network

echo "#################"
echo "     RUNNING     "
echo "#################"

./network
